apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-express-cronjob
  namespace: mongo-db
spec:
  suspend: true
  schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mongo-express-pods
        spec:
          containers:
            - name: mongo-express-container
              image: mongo-express:latest
              ports:
                - containerPort: 8081
              env:
                - name: ME_CONFIG_MONGODB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: mongo-config-map
                      key: DB_URL
                - name: ME_CONFIG_BASICAUTH_USERNAME
                  value:
                - name: ME_CONFIG_BASICAUTH_PASSWORD
                  value:
                - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
                  value: "true"
                - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: DB_USER
                - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: DB_PASSWORD
          restartPolicy: OnFailure
