apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo-db
spec:
  selector:
    app: mongo-express-pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
      nodePort: 30001
  type: LoadBalancer
