apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongo-db
spec:
  selector:
    app: mongodb-pods
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
